<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><AssemblyName>ClassicDesk</AssemblyName>
    <Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><UseAppHost>true</UseAppHost>
    <RestoreSources></RestoreSources><NuGetAudit>false</NuGetAudit>
  </PropertyGroup>
  <ItemGroup><Compile Include="../../src/ClassicDesk/FrontendUpdateModels.cs;../../src/ClassicDesk/FrontendUpdateInstaller.cs" Link="%(Filename)%(Extension)" /></ItemGroup>
</Project>
